PROJECT_NAME=mctests
PROJECT_ROOT=$(realpath .)
BASE_OBJ_DIR=$(PROJECT_ROOT)/obj
BASE_LIB_DIR=$(PROJECT_ROOT)/lib
BASE_BIN_DIR=$(PROJECT_ROOT)/bin
BASE_GEN_DIR=$(PROJECT_ROOT)
BASE_SRC_DIR=$(PROJECT_ROOT)

CXX?=g++
CXXFLAGS+=-std=c++11 -Wall -pedantic -Wno-gnu-folding-constant -pipe
CXXFLAGS+=-I/usr/local/Cellar/google-sparsehash/2.0.2/include/sparsehash/ -I/usr/local/include/

PROJECT_EXECUTABLES=PingPongChan Elevator Flip FlipSimple PingPongChanBug ABP \
	ABP_generated MSI Fischer LeaderElection Dijkstra4 MSI_no_busy_data_no_pending_unblock_e \
	MSIC2D PingPongChanSynth MSISynth
#	WeakestPreconditionTest
#	WeakestPreconditionArrayTest
#   ElevatorBug

libesmc_FULL_PATH=$(PROJECT_ROOT)/../../lib/$(BUILD_SUFFIX)/libesmc.so
libesmc_MAKE_DIR=$(PROJECT_ROOT)/../../

$(foreach exec, $(PROJECT_EXECUTABLES), $(eval $(exec)_SYS_LIBS=esmc z3 boost_program_options))
$(foreach exec, $(PROJECT_EXECUTABLES), $(eval $(exec)_EXT_LIBS=boost_program_options z3 esmc))
$(foreach exec, $(PROJECT_EXECUTABLES), $(eval $(exec)_OBJS=$(exec).o))
$(foreach exec, $(PROJECT_EXECUTABLES), $(eval $(exec)_LIB_PATHS=$(PROJECT_ROOT)/../../lib/$(BUILD_SUFFIX)))

include $(PROJECT_ROOT)/../../Makefile.mac.util
